### ISSUE TITLE
Unions not working

### ISSUE THREAD

**Issue by vladinator1000** [Urigo/graphql-modules#619]
Hey y'all, found a bug. I can't get unions to resolve to other types.
Here's a [reproduction Codesandbox](https://codesandbox.io/s/github/savovs/gql-modules-union/tree/master/?fontsize=14&initialpath=%2Fgraphql&module=%2Fsrc%2Fmodules%2Fconcert%2Fconcert.resolvers.ts) to make your life easy

GitHub: https://github.com/savovs/gql-modules-union/

When I send a query like this one:
```gql
{
  featuredConcert {
    organiser {
      ... on Venue {
        name
        address
      }
      ... on Artist {
        name
        genre
      }
    }
  }
}
```

I'm expecting `__resolveType` on a union resolver like [this one](https://github.com/savovs/gql-modules-union/blob/master/src/modules/concert/concert.resolvers.ts#L7) to get called but it doesn't. 

Getting this error when I send the query in the playground:
```
 "Abstract type Organiser must resolve to an Object type at runtime for field Concert.organiser with value { id: 1, name: \"Birdland Jazz Club\", address: \"533 Peachtree Place\", type: \"venue\" }, received \"undefined\". Either the Organiser type should provide a \"resolveType\" function or each possible type should provide an \"isTypeOf\" function."
```

I also tried adding a ` __isTypeOf` function to each possible type but that resulted in another error:
```
TypeError: Cannot read property 'session' of undefined",
                  "    at GraphQLObjectType.typeResolvers.<computed> [as isTypeOf] (/mnt/c/Users/Vlady/Documents/Code/gql-unions/node_modules/@graphql-modules/core/src/graphql-module.ts:1080:37)",
                  "    at defaultTypeResolver (/mnt/c/Users/Vlady/Documents/Code/gql-unions/node_modules/graphql/execution/execute.js:798:33)",
                  "    at completeAbstractValue (/mnt/c/Users/Vlady/Documents/Code/gql-unions/node_modules/graphql/execution/execute.js:686:21)",
                  "    at completeValue (/mnt/c/Users/Vlady/Documents/Code/gql-unions/node_modules/graphql/execution/execute.js:621:12)",
                  "    at /mnt/c/Users/Vlady/Documents/Code/gql-unions/node_modules/graphql/execution/execute.js:528:16",
                  "    at processTicksAndRejections (internal/process/task_queues.js:85:5)",
```

It works if you do it with a monolith schema [like this](https://github.com/savovs/gql-modules-union/blob/monolith/src/monolithSchema.ts) but that defeats the purpose of using graphql-modules for me.

How do we handle this? I'm a little confused here.

**Comment by ardatan** [comment]
First, I added tests for resolveType resolver. I think there is a problem about merging schemas inside modules in ApolloServer, because it worked in our tests. I can suggest you to have a single AppModule on top.
https://github.com/Urigo/graphql-modules/pull/621/files
You can see the tests to see how I built the relationship between modules.
Secondly, I reproduced the issue related to `__isTypeOf` and I fixed it.
You can find this fixed version of GraphQL Modules under the following canary version;
`0.7.10-alpha-de43ec4.19+de43ec4  `

**Comment by ardatan** [comment]
@vladinator1000 What's the current status about this issue?

**Comment by NikxDa** [comment]
@ardatan `__resolveType` is still not being called for me with version 7.10. Stuck big time with this one. Any fix in sight?

**Comment by ardatan** [comment]
@NikxDa Try passing top module's schema like below instead of using `modules` property
```
{
schema: AppModule.schema,
context: session => session,
}
```

**Comment by NikxDa** [comment]
@ardatan That does the trick, but why does it not work with the `modules` property? Does this solution have any other impacts?

**Comment by devtim123** [comment]
Hey, i also noticed this bug, and can not resolve it by using a standalone project wide graphql-modules schema. I don't know if the reason could be that i using typegraphql or apollo-server.

i wrote a simple GraphQL-Apollo-Server example demonstrate a bug when using unions in combination with graphql-modules + typegraphql + apollo-server. would like to know how to solve this problem or how to debug it. GitHub-Repo: https://github.com/devtim123/graphql-modules-union-example

commands to reproduce the issue:
```
git clone git@github.com:devtim123/graphql-modules-union-example.git
cd graphql-modules-union-example
yarn install
yarn dev
```
and visit http://localhost:4000/api

start query at playground:
```
query example {
  example {
    __typename
    ... on Actor {
      name
      age
    }
    ... on Movie {
      name
      rating
    }
  }
}

```

expected result:
```
{
  "data": {
    "example": {
      "__typename": "Movie",
      "name": "Fight Club",
      "rating": 999
    }
  }
}
```

current result:
```
{
  "data": {
    "example": {
      "__typename": "Movie"
    }
  }
}
```

For this simple example, creating the schema via (see Line #15 @ src/server.ts), the resolver works as expected:

```
const schema = await buildSchema({
    resolvers: [rootModule.resolvers]
});
```

But this works not in larger GraphQL-Modules projects, where i get the following error on startup:

```
TypeError: Cannot convert undefined or null to object
```

I hope we can find a solution there...

thank you for any help, best regards, tim

**Comment by fridaystreet** [comment]
I'm also seeing this issue still happening and I'm passing my top level module schema to apollo-server. Still the __resolverType function is never called.

Any further thoughts on this?

**Comment by justinmchase** [comment]
Supposing I have multiple modules, how can I convert them into a single schema? And if I can do this why can't apollo server? 

This bug should not have been closed as it appears to still be active with no solution in a case where you actually want to have multiple modules.

**Comment by maapteh** [comment]
@justinmchase vladinator did:

```
const apolloServer = new ApolloServer({
	modules,
	context: ({ req, res }: any) => ({ req, res })
})
```

which gave the error. You still have multiple modules inside your setup off course. You just have to include the schema not the modules like Ardatan said.

So maybe this helps anyone :)

```
export const AppModule: GraphQLModule = new GraphQLModule({
    name: 'app',
    imports: [
        FooModule,
        BarModule,
        ShizzleModule,
    ],
});
```

and then:

```
const apolloServer = new ApolloServer({
	schema: Appmodule.schema,
	context: ({ req, res }: any) => ({ req, res })
})
```

**Comment by mabreuortega** [comment]
I having the same issue on 1.0.0-alpha.2

`/Users/miguel.abreu/repos/admin-tool-migration-destination/namespaces/ent-tools/projects/admin-tool/dist/graphql-modules/src/module/resolvers.js:153
    container[typeName].__resolveType = fields.__resolveType;
                                     ^
TypeError: Cannot set property '__resolveType' of undefined
    at addInterfaceOrUnion (/Users/miguel.abreu/repos/admin-tool-migration-destination/namespaces/ent-tools/projects/admin-tool/dist/graphql-modules/src/module/resolvers.js:153:38)
    at mergeResolvers (/Users/miguel.abreu/repos/admin-tool-migration-destination/namespaces/ent-tools/projects/admin-tool/dist/graphql-modules/src/module/resolvers.js:132:21)
    at createResolvers (/Users/miguel.abreu/repos/admin-tool-migration-destination/namespaces/ent-tools/projects/admin-tool/dist/graphql-modules/src/module/resolvers.js:11:43)
    at Object.factory (/Users/miguel.abreu/repos/admin-tool-migration-destination/namespaces/ent-tools/projects/admin-tool/dist/graphql-modules/src/module/factory.js:42:40)
    at /Users/miguel.abreu/repos/admin-tool-migration-destination/namespaces/ent-tools/projects/admin-tool/dist/graphql-modules/src/application/application.js:44:53
    at Array.map (<anonymous>)
    at Object.createApplication (/Users/miguel.abreu/repos/admin-tool-migration-destination/namespaces/ent-tools/projects/admin-tool/dist/graphql-modules/src/application/application.js:44:36)
    at Object.<anonymous> (/Users/miguel.abreu/repos/admin-tool-migration-destination/namespaces/ent-tools/projects/admin-tool/packages/server/src/application.ts:6:28)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Module.m._compile (/Users/miguel.abreu/repos/admin-tool-migration-destination/namespaces/ent-tools/projects/admin-tool/node_modules/ts-node/src/index.ts:858:23)`

**Comment by sahanatroam** [comment]
@Urigo why was this issue closed? I think this issue still exists

**Comment by sahanatroam** [comment]
@Urigo @dotansimha This is still an issue, exactly the issue above.
