### ISSUE TITLE
ts error in `graphql-toolkit` when compiling

### ISSUE THREAD

**Issue by maapteh** [Urigo/graphql-modules#669]
i went from 0.4 to 0.7 so maybe i missed something crucial in the upgrade path but somehow my app is not compiling anymore. Example:

`node_modules/@graphql-modules/core/node_modules/graphql-toolkit/dist/esnext/utils/validate-documents.d.ts:7:129 - error TS1005: ',' expected.`

`export declare const validateGraphQlDocuments: (schema: GraphQLSchema, documentFiles: DocumentFile[], effectiveRules?: readonly import("graphql").ValidationRule[]) => readonly LoadDocumentError[];`

**Comment by dotansimha** [comment]
Fixed by @kamilkisiela in https://github.com/ardatan/graphql-toolkit/pull/230 
Keeping open until we'll release `graphql-toolkit` and then `graphql-modules.

**Comment by ardatan** [comment]
Fixed in 0.7.12 :)

**Comment by maapteh** [comment]
nope
```
../../node_modules/@graphql-modules/core/node_modules/graphql-toolkit/dist/esnext/utils/validate-documents.d.ts:8:150 - error TS1005: ',' expected.

8 export declare const validateGraphQlDocuments: (schema: GraphQLSchema, documentFiles: DocumentFile[], effectiveRules?: ValidationRule[]) => readonly LoadDocumentError[];
                                                                                                                                                       ~~~~~~~~~~~~~~~~~

../../node_modules/@graphql-modules/core/node_modules/graphql-toolkit/dist/esnext/utils/validate-documents.d.ts:8:167 - error TS1005: ',' expected.

8 export declare const validateGraphQlDocuments: (schema: GraphQLSchema, documentFiles: DocumentFile[], effectiveRules?: ValidationRule[]) => readonly LoadDocumentError[];
```

graphql-tookit 0.5.13 inside graphql-modules 0.7.12

**Comment by Urigo** [comment]
@maapteh why did you reopened the issue?

**Comment by maapteh** [comment]
Ah sorry, i have too many right overhere i think :)

I reopened because the issue still ocurs, less faults but still 2:

1. `git clone https://github.com/maapteh/graphql-modules-app.git`
2. `yarn`
3. `yarn workspace graphql-server buildFIXME`

**Comment by Urigo** [comment]
thanks for the context!

**Comment by ardatan** [comment]
@maapteh I reproduced the same error with the old TS version in server's package.json `3.2.1` and when  I updated it to `3.6.3`, it built successfully.
I think it happens because we use a new syntax or something in graphql-toolkit.

**Comment by maapteh** [comment]
Thanks for this update @ardatan i will update. I know TS is optional in modules, but maybe it should become clear you at least need version x?

**Comment by ardatan** [comment]
Yes, we will update documentation about TypeScript version compability.

**Comment by ardatan** [comment]
Updated!

**Comment by kamilkisiela** [comment]
@ardatan what was the cause? Usually what's incompatible are built-in helper types  like `Exclude`, `Extract` and so on but also `readonly string[]` and this kind of things. We can achieve better compatibility by replacing those with for example `ReadonlyArray<string>`.

**Comment by ardatan** [comment]
@kamilkisiela Then, I'll create a PR to change `readonly string[]` to `ReadonlyArray<string>`.
